version: '1.0'
services:
  mongodb:
    image: mongo:5
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    container_name: auth-server
    ports:
      - 4001:3001
    env_file:
      - .env
    depends_on:
      - mongodb

  event:
    build:
      context: .
      dockerfile: ./apps/event/Dockerfile
    container_name: event-server
    ports:
      - 4002:3002
    env_file:
      - .env
    depends_on:
      - mongodb

  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    container_name: gateway-server
    ports:
      - 4000:3000
    env_file:
      - .env
    depends_on:
      - auth
      - event
      - mongodb

volumes:
  mongo_data:
